---
title: "Анализ данных с производства"
author: ""
date: '`r Sys.Date()`'
fontsize: 12pt
output:
  pdf_document:
    dev: cairo_pdf
    keep_tex: yes
    latex_engine: xelatex
    includes:
        in_header: mystyles.sty
---


```{r setup, include=FALSE}
# Инициализация пакетов
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, fig.width=7)
knitr::opts_chunk$set(dev='cairo_pdf') # решили проблему с генерацией русского текста в графиках
```

```{r echo=FALSE}
library(tidyverse)
library(lubridate)
library(magrittr)
library(stringi)
library(stringr)
library(readxl)
library(iterators)
library(foreach)
library(doParallel)
library(zoo)
library(tictoc)
library(extrafont)
library(hrbrthemes)
library(xtable)
library(knitr)


datafile <- "./data/2016.xlsx"
```

```{r}
# Определение функции загрузки
get_month_data <- function(filename, sheetname="") {
  # хак по считыванию типов колонок
  raw <- read_excel(filename)
  ncol(raw)
  ctypes <- rep("text", 146)
  cnames <- str_c("grp_", seq_along(ctypes))
  raw <- read_excel(filename,
                   sheet=sheetname,
                   #col_names=cnames,
                   col_types=ctypes,
                   range = cell_cols("A:EP")) #, skip = 1)
  
  # имеем проблему, колонки с NA вместо имени
  # можно писать в одно преобразование, но специально разбил на шаги
  # трансформируем колонки
  df0 <- raw %>%
    repair_names(prefix="repaired_", sep="")
  
  # названия колонок размазаны по строкам 2-3. 2-ая -- группирующая, 3-я -- детализирующая
  # Надо их слить и переименовать колонки, причем приоритет имеет строка 3, как уточняющая
  #name_c2 <- tidyr::gather(df0[1, ], key = name, value = name_c2) # 1-ая колонка ушла в имена
  #name_c3 <- tidyr::gather(df0[2, ], key = name, value = name_c3) # 2-ая колонка ушла в имена
  
  # различные виды join не подойдут, поскольку мы хотим оставить все строки, вне зависимости от результата
  # сливать по именам опасно, вдруг есть дубли
  # names.df <- dplyr::full_join(name_c2, name_c3, by = "name")
  names_df <- tibble(name_c2=tidyr::gather(df0[1, ], key=name, value=v)$v,
                     name_c3=tidyr::gather(df0[2, ], key=name, value=v)$v) %>%
    # http://www.markhneedham.com/blog/2015/06/28/r-dplyr-update-rows-with-earlierprevious-rows-values/
    mutate(name_c2 = na.locf(name_c2)) %>%
    # если name_c3 = NA, то результат объединения строк также будет NA, нас это не очень устраивает
    mutate(name_fix = ifelse(is.na(name_c3), name_c2, str_c(name_c2, name_c3, sep=": "))) %>%
    mutate(name_fix = str_replace_all(name_fix, "\r", " ")) %>% # перевод строки
    mutate(name_fix = str_replace_all(name_fix, "\n", " ")) %>% # перевод строки
    mutate(name_fix = str_replace_all(name_fix, "  ", " "))
  
  # browser()
  df1 <- df0
  repl_df <- tribble(
    ~pattern, ~replacement,
    "Мастер-технолог", "foreman_tech",
    "Формующая часть: Угол напорного ящика", "angle_in",
    "Формующая часть: Разница скорости струи/сетки", "speed_diff_in",
    "Формующая часть: Открытие щели напорного ящика", "slot_in",
    "Формующая часть: Давление на напорном ящике", "pressure_in",
    "Формующая часть: Скорость смесительного насоса", "mix_pump_in",
    "Прессовая часть: Натяжение сукна", "cloth_tension",
    "Прессовая часть: Вакуум 1-я сукномойка", "vacuum_1",
    "Поток: Концентрация при размоле", "concentration_in",
    "1-ой рафинер: Удельное потребление энергии", "energy_per_rafiner1",
    "Янки-циллиндр: Давление пара Янки цилиндра", "yanki_steam",
    "Адгезив: Расход по факту", "adhesive_fact",
    "Релиз: Расход по факту", "release_fact",
    "Производительность", "performance_out",
    "Вес м2", "weight_out",
    "Артикул", "mark_out",
    "Примечание", "notes"
  )
  names(df1) <- stri_replace_all_fixed(names_df$name_fix,
                                       pattern = repl_df$pattern,
                                       replacement = repl_df$replacement,
                                       vectorize_all = FALSE)
  # Все равно кривые имена, дубли
  names_df %>% 
    group_by(name_fix) %>% 
    filter(n()>1)
  
  df1 %<>% repair_names(prefix = "repaired_", sep = "")
  
  # выбираем только интересующие колонки
  df2 <- df1 %>% 
    select(foreman_tech, angle_in, speed_diff_in, slot_in, pressure_in, concentration_in,
           performance_out, weight_out, mark_out, notes, mix_pump_in, yanki_steam, cloth_tension,
           vacuum_1, energy_per_rafiner1, adhesive_fact, release_fact) %>%
    filter(row_number() > 6) # удаляем весь верхний шлак
  # browser()
  
  df3 <- df2 %>%
    # filter(complete.cases(.)) %>% # удаляем строки, содержащие пустые данные
    filter(performance_out>0) %>%
    # distinct() %>% # уберем идентичные строчки
    #http://stackoverflow.com/questions/27027347/mutate-each-summarise-each-in-dplyr-how-do-i-select-certain-columns-and-give
    mutate_at(vars(-foreman_tech, -mark_out, -notes), funs(as.numeric))
  
  df3
}

```

# Консолидация Excel файла
```{r results = 'asis'}
mnames <- c("Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", 
            "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь")

tmp <- excel_sheets(datafile)
sheets <- tmp[tmp %in% mnames]

df <- foreach(it=iter(sheets), .combine=rbind, .packages='readxl') %do% {
  temp.df <- get_month_data(datafile, it) %>% mutate(month=it)

  temp.df
}

# наверное данные без маркировки выходной продукции не имеют большого смысла
df %<>% filter(!is.na(mark_out))

kable(df %>% select(month, foreman_tech, mark_out, performance_out, notes), caption="Исходные данные")
# print(xtable(df), comment=FALSE)

```

```{r eval=FALSE}
tic("Analysis")
# посчитаем количество уникальных значений в колонках
dist_cols <- map_df(select(df, everything()), n_distinct)
# посчитаем и отсортируем словарные уникальные значения
unq <- map(df, unique) %>% map(sort, decreasing=T)
toc()

dist_cols
unq


```

# Визуализация данных по результатам предварительной коммуникации с экспертами
```{r eval=FALSE}
extrafont::loadfonts()
extrafont::fonttable()
extrafont::fonts()
```


```{r}
df0 <- df %>% 
  group_by(mark_out, month, foreman_tech) %>% 
  summarise(performance = mean(performance_out)) %>%
  arrange(desc(mark_out)) %>%
  top_n(1, wt=performance)
  # mutate(num=row_number()) 

# df0

# Лучший мастер по производительности на каждый вид бумаги
gp <- ggplot(df0, aes(x=month, y=performance, fill=foreman_tech)) + 
  geom_col() +
  theme_ipsum_rc(base_size = 11.5) +
  facet_wrap(~mark_out) +
  ggtitle("Лучший мастер по производительности")

gp

```

```{r}
# Средняя speed_diff_in для каждого вида бумаги

gp <- ggplot(df, aes(x=mark_out, y=speed_diff_in)) + 
  geom_point() +
  # theme_ipsum_rc(base_family="Roboto Condensed", base_size = 11.5)
  theme_ipsum_rc(base_size = 11.5) +
  ggtitle("Разница скорости струи/сетки от вида бумаги",
          subtitle="Для различных видов бумаги")

gp

```

```{r}
# Производительность машины по месяцам
gp <- ggplot(df, aes(x=month, y=performance_out, fill=foreman_tech)) + 
  geom_col() +
  theme_ipsum_rc(base_size = 11.5) +
  ggtitle("Производительность машины")

gp

```


```{r fig.height=7}
# Зависимость speed_diff_in от slot_in
gp <- ggplot(df, aes(x=slot_in, y=speed_diff_in, colour=mark_out)) + 
  geom_point() +
  # theme_ipsum_rc(base_family="Roboto Condensed", base_size = 11.5)
  theme_ipsum_rc(base_size = 11.5) +
  facet_wrap(~mark_out, scales = "free") +
  ggtitle("Разница скорости струи/сетки от щели открытия",
          subtitle="Для различных видов бумаги")

gp

```
```{r}
# Расход химикатов по факту адгезив и релиз от коэффициента напуска

gp <- ggplot(df, aes(x=speed_diff_in, y=adhesive_fact)) + 
  geom_point() +
  theme_ipsum_rc(base_size=11.5) +
  ggtitle("Расход по факту химиката 'Адгезив'", 
          subtitle="В зависимости от от коэффициента напуска")

gp

```
```{r}
# Расход химикатов по факту адгезив и релиз от коэффициента напуска

gp <- ggplot(df, aes(x=speed_diff_in, y=release_fact)) + 
  geom_point() +
  theme_ipsum_rc(base_size=11.5) +
  ggtitle("Расход по факту химиката 'Релиз'", 
          subtitle="В зависимости от от коэффициента напуска")

gp

```

```{r}
# Давление пара на янки-цилиндре от удельного потребления энергии на рафинёре №1 + концентрация при размоле как фактор

gp <- ggplot(df, aes(x=energy_per_rafiner1, y=yanki_steam, colour=concentration_in)) + 
  geom_point() +
  theme_ipsum_rc(base_size=11.5) +
  # facet_wrap(~concentration_in, scales = "free") +
  ggtitle("Давление пара на янки-цилиндре", 
          subtitle="В зависимости от удельного потребления энергии на рафинёре №1")

gp

```


```{r}
# Вакуум от натяжения сукон

gp <- ggplot(df, aes(x=cloth_tension, y=vacuum_1)) + 
  geom_point() +
  # geom_smooth(method="lm", span=0.8) +
  # geom_smooth(span=0.8) +
  # theme_ipsum_rc(base_family="Roboto Condensed", base_size = 11.5)
  theme_ipsum_rc(base_size=11.5) +
  ggtitle("Вакуум в 1-ой сукномойке", 
          subtitle="В зависимости от натяжения сукна")

gp

```
```{r}
gp <- ggplot(df, aes(x=pressure_in, y=mix_pump_in)) + 
  geom_point() +
  # geom_smooth(method="lm", span=0.8) +
  geom_smooth(span=0.8) +
  # theme_ipsum_rc(base_family="Roboto Condensed", base_size = 11.5)
  theme_ipsum_rc(base_size=11.5) +
  ggtitle("Давление в напорном ящике", 
          subtitle="В зависимости от скорости смесительного насоса")

gp

```
