---
title: "R Notebook"
output: html_notebook
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyr)
library(magrittr)
library(purrr)
library(stringi)
library(stringr)
library(tibble)
library(readxl)
library(iterators)
library(foreach)
library(doParallel)
library(zoo)
library(gtable)
library(grid) # для grid.newpage()
library(gridExtra) # для grid.arrange()
library(RColorBrewer)
library(microbenchmark)
library(futile.logger)
# часть файлов пришлось открывать в Excel вручную и пересохранять в формате последнего Excel,
# There is a problem with reading some xlsx files 
# (not the ones generated by Google Docs - this is some other xlsx generating BI)

source("common_funcs.R")

common_log_name <- "SAP_crosscheck.log"

flog.appender(appender.file(common_log_name))
flog.threshold(TRACE)
flog.info("============= Parsing started ===============")


rep2 <- loadReportsType2("./data-verification/Отчет (отчет №2) 022, 056.xlsx")
rep3 <- loadReportsType3("./data-verification/")
rep1 <- loadReportsType1("./data-verification/")
```
# Проверка отчета в разрезе ОИП (отчет №1)

## Отчет #1: Перечень ОИП которых нет в отчете №1
```{r}
subrep1 <- rep1 %>%
  filter(str_detect(grp_1, '\\d{3}-\\d{7}$')) %>% # Только родительские ОИП
  select(grp_1) %>%
  rename(oip=grp_1)

subrep2 <- rep2 %>%
  filter(str_detect(col_A, '\\d{3}-\\d{7}$')) %>% # Только родительские ОИП
  select(col_A) %>%
  rename(oip=col_A)

check_1 <- anti_join(subrep2, subrep1, by="oip") %>% arrange(oip)

check_1
```
## Отчет #2: Перечень ОИП с разными наименованиями
```{r}
check_2 <- rep1 %>%
  select(grp_1, grp_2) %>%
  group_by(grp_1, grp_2) %>%
  summarise(records=n()) %>%
  filter(records>1)
```

