library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyr)
library(magrittr)
library(purrr)
library(stringi)
library(stringr)
library(tibble)
library(readxl)
library(iterators)
library(foreach)
library(doParallel)
library(zoo)
library(gtable)
library(grid) # для grid.newpage()
library(gridExtra) # для grid.arrange()
library(RColorBrewer)
library(microbenchmark)
library(futile.logger)
# часть файлов пришлось открывать в Excel вручную и пересохранять в формате последнего Excel,
# There is a problem with reading some xlsx files 
# (not the ones generated by Google Docs - this is some other xlsx generating BI)

source("common_funcs.R")

common_log_name <- "SAP_crosscheck.log"

flog.appender(appender.file(common_log_name))
flog.threshold(TRACE)
flog.info("============= Parsing started ===============")


rep2 <- loadReportsType2("./data-verification/Отчет (отчет №2) 022, 056.xlsx")
rep3 <- loadReportsType3("./data-verification/")
rep1 <- loadReportsType1("./data-verification/")

# -- Проверка 'Перечень ОИП которых нет в отчете №X'
subrep1 <- rep1 %>%
  select(grp_1) %>%
  filter(str_detect(grp_1, '\\d{3}-\\d{7}$')) %>% # Только родительские ОИП
  rename(oip=grp_1)

subrep2 <- rep2 %>%
  select(col_A) %>%
  filter(str_detect(col_A, '\\d{3}-\\d{7}$')) %>% # Только родительские ОИП
  rename(oip=col_A)

check_1 <- anti_join(subrep2, subrep1, by="oip") %>% arrange(oip)

# -- Проверка 'Перечень ОИП с разными наименованиями'
subrep1 <- rep1 %>%
  select(grp_1, grp_2) %>%
  rename(oip=grp_1, name=grp_2) %>%
  filter(str_detect(oip, '\\d{3}-\\d{7}$')) # Только родительские ОИП

subrep2 <- rep2 %>%
  select(col_A, col_B) %>%
  rename(oip=col_A, name=col_B) %>%
  filter(str_detect(oip, '\\d{3}-\\d{7}$')) # Только родительские ОИП

check_2 <- dplyr::setdiff(subrep1, subrep2)
stop()


subrep1 <- rep1 %>%
  select(grp_1, grp_2) %>%
  filter(str_detect(grp_1, '\\d{3}-\\d{7}$')) %>% # Только родительские ОИП
  mutate(joint = str_c(grp_1, grp_2, sep=" ")) %>%
  rename(oip=grp_1)

subrep2 <- rep2 %>%
  select(col_A, col_B) %>%
  filter(str_detect(col_A, '\\d{3}-\\d{7}$')) %>% # Только родительские ОИП
  mutate(joint = str_c(col_A, col_B, sep=" ")) %>%
  rename(oip=col_A)

check_2 <- anti_join(subrep2, subrep1, by="oip") %>% arrange(oip)

stop()


# -- Проверка 'Перечень ОИП с разными наименованиями'

check_2 <- rep1 %>%
  select(grp_1, grp_2) %>%
  group_by(grp_1, grp_2) %>%
  summarise(records=n()) %>%
  filter(records>1)

stop()
# dir(path="./data-verification/", pattern="*№3*.xl*", full.names=TRUE)
# dir(path="./data-verification/", pattern="^(?!~).*№\\s*3", full.names=TRUE)
# stri_match_all_regex(basename_matches, pattern='^.*/(?!\\~)[^/]*?\\.xl.*$')

file_names <- getExcelFileList("./data-verification/", pattern="*№\\s*3")
write(file_names, file="test.txt")
fname <- stri_enc_toutf8(file_names[[1]])
fname <- file_names[[1]]
raw <- read_excel(fname)
col_types <- readxl:::xlsx_col_types(fname)
col_types <- readxl:::xlsx_col_types("./data-verification/022 - Отчет о см. ст. по ОКС (Отчет №3).xlsx")
