---
title: "R Notebook"
output:
  html_notebook: default
---


```{r echo=FALSE, message=FALSE}
# 
library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyr)
library(magrittr)
library(purrr)
library(stringi)
library(stringr)
library(tibble)
library(readxl)
library(iterators)
library(foreach)
library(doParallel)
library(zoo)
library(grid) # для grid.newpage()
library(gridExtra) # для grid.arrange()
library(RColorBrewer)
library(rmarkdown)
library(xtable)
```

```{r}
source("common_funcs.R")

# файл с исходными данными
data_filename <- "./data/отчет с детализацией по ОКС (056-2000815, 022-2000791, 051-2002476).xlsx"

df <- getOksData(data_filename)
df_gp <- df %>%
  group_by(year) %>%
  summarise(num=n(), pd=sum(pd_cost), smp=sum(smp_cost), plant=sum(plant_cost))
xlims <- c(min(df_gp$year)-1, max(df_gp$year)+1)
```

Загруженный набор данных, диапазон годов: `r xlims`
```{r}
# print(xtable(df_gp), type="html")
df_gp

# knitr::kable(df_gp)
```

```{r}
# -- Затраты на ОКС по годам
df_gp1 <- df_gp %>%
  select(-num) %>%
  gather(key=type, value=cost, -year) # превратили в long для отрисовки


gp1 <- ggplot(data = df_gp1, aes(x=year, y=cost, fill=type)) +
  theme_bw() +
  # theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  scale_fill_brewer(palette="Set1", direction=1, guide=guide_legend()) +
  geom_bar(stat="identity", position="dodge") +
  theme(legend.position="top") +
  #geom_point(size = 3, fill = "yellow", shape = 21, na.rm = TRUE) +    # White fill
  #geom_abline(intercept = 0, slope = 1, colour = "red") +
  scale_x_continuous(limits=xlims, breaks=seq(xlims[[1]], xlims[[2]], 1)) +
  #scale_x_continuous(breaks=seq(xlims[[1]], xlims[[2]], 1)) +
  #coord_cartesian(xlim=xlims) +
  labs(x="Год", y="Сметная стоимость\n по ПД, руб.")
gp1
```

```{r}
# -- количество ОКС по годам
df_gp2 <- df_gp %>%
  select(year, num)

gp2 <- ggplot(data = df_gp2, aes(x=year, y=num)) +
  theme_bw() +
  geom_point(size=3, fill="yellow", shape=21, na.rm=TRUE) +    # White fill
  geom_line(colour="blue") +
  scale_x_continuous(limits=xlims, breaks=seq(xlims[[1]], xlims[[2]], 1)) +
  labs(x="Год", y="Количество ОКС, ед.")
gp2
```

