---
title: "R Notebook"
author: "ishutov"
date: 17.03.2017
output:
  html_notebook: default
  html_document: default
resource_files:
- edr_BASE-edr_http_format_03092017143656_002_002808698
- edr_BASE-edr_http_format_03092017143702_002_002808699
- edr_BASE-edr_http_format_03092017143707_002_002808700
- edr_BASE-edr_http_format_03092017143713_002_002808701
- edr_BASE-edr_http_format_03092017143750_002_002808707
- edr_BASE-edr_http_format_03092017143756_002_002808708
- edr_BASE-edr_http_format_03092017143801_002_002808709
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=FALSE}
library(tidyverse)
library(forcats)
library(magrittr)
library(stringi)
library(scales)
library(ggthemes)
library(gtable)
library(Cairo)
library(hrbrthemes)
library(RColorBrewer)
```


# Загрузка исходных данных

```{r}

# Reading and combining many tidy data files in R, Jun 13, 2016 in science
# http://serialmentor.com/blog/2016/6/13/reading-and-combining-many-tidy-data-files-in-R

http_list <- dir(path="./", pattern="edr_BASE-edr_http_format_.*", full.names=TRUE)
```

Импортируемый список файлов:
`r http_list`

```{r message=FALSE, warning=FALSE}
df <- http_list %>%
  purrr::map_df(read_delim, delim=',', .id = NULL) %>%
  repair_names()

```


```{r}

# преобразования -----------------------------------------
# очистим имена колонок от кривых символов
fix_names <- names(df) %>%
  stri_replace_all_fixed(pattern=c("#", "-", " "), replacement=c("", "_", "_"), vectorize_all=FALSE)

names(df) <- fix_names

df1 <- df %>%
  mutate(start_timestamp=as.POSIXct(sn_start_time, origin="1970-01-01", tz="Europe/Moscow")) %>%
  mutate(end_timestamp=as.POSIXct(sn_end_time, origin="1970-01-01", tz="Europe/Moscow")) %>%
  mutate(downlink_bytes=as.numeric(transaction_downlink_bytes)) %>%
  mutate(uplink_bytes=as.numeric(transaction_uplink_bytes)) %>%  
  select(start_timestamp, end_timestamp, everything())
```

```{r include=FALSE}
# посмотрим параметры полученных xDR
cat(sprintf("Минимальное время закрытия:  %s\nМаксимальное время закрытия: %s\nUplink:   %s Мб\nDownlink: %s Гб",
            min(df1$end_timestamp), 
            max(df1$end_timestamp),
            round(sum(df1$uplink_bytes)/1024^2, 1),
            round(sum(df1$downlink_bytes)/1024^3, 1)
            )
)

group_df <- df1 %>%
  slice(1:20000) %>%
  group_by(radius_user_name) %>%
  summarise(user_recs=n(), 
            uplink_Kb=round(sum(uplink_bytes)/1024, 1), 
            downlink_Kb=round(sum(downlink_bytes)/1024, 1)) %>%
  arrange(desc(user_recs))
```

# TOP-10 пользователей
```{r}

plot_df <- group_df %>%
  top_n(10, downlink_Kb) %>%
  mutate(downlink_Mb=downlink_Kb/1024) %>%
  arrange(desc(downlink_Kb))

# windowsFonts(robotoC="Roboto Condensed")

gp <- ggplot(plot_df, aes(fct_reorder(radius_user_name, downlink_Mb), downlink_Mb)) + 
  geom_bar(fill=brewer.pal(n=9, name="Blues")[4], alpha=0.5, stat="identity") +
  #theme_igray() +
  # theme_ipsum_rc(base_family="robotoC", base_size = 11.5) +
  theme_ipsum_rc(base_size = 11.5) +
  theme(legend.position="none") +
  xlab("Raduis хэш") +
  ylab("Суммарный Downlink, Mb") +
  coord_flip()

gp

```
```{r}
 # gtable_show_layout(ggplotGrob(gp))
df2 <- df1 %>%
  #slice(1:20000) %>%
  select(timestamp=end_timestamp, downlink_bytes, uplink_bytes) %>%
  gather(downlink_bytes, uplink_bytes, key="direction", value="bytes") %>%
  sample_frac(0.2) %>%
  filter(bytes>0.1)

gp2 <- ggplot(df2, aes(timestamp, bytes)) + 
  geom_point(aes(colour=direction), alpha=0.4, shape=1, size=2) +
  theme_ipsum_rc(base_size = 11.5) +
  theme(legend.position="right") +
  scale_y_log10(breaks=trans_breaks("log10", function(x) 10^x),
                labels=trans_format("log10", math_format(10^.x)))

gp2
```



